### ISSUE TITLE
Please display the Z-offset on the printing screen 

### ISSUE THREAD

**Issue by ztakis** [CR6Community/Marlin#114] opened 2021-01-01 13:26 UTC
### Description

Print Screen does not display Z-offset

**Expected behavior:** 

All other info is shown, why not Z-offset?

**Comment by Sebazzz** [comment] 2021-01-01 15:10
This is by design. In our opinion the Z offset is not necessary compared to the other data points. You set and forget, or tune it from the tuning screen.

**Comment by ztakis** [comment] 2021-01-01 16:08
I believe it is helpful as a reminder, especially if someone is using various nozzles from different manufacturers.
And more than once I have change it in real time when I noticed that the first layer didn't came out as expected.

**Comment by Sebazzz** [comment] 2021-01-02 08:48
Changing it in real time would still happen in the tuning screen.

Assigning this to @grobux to see if we still have some space somewhere for this.

**Comment by ztakis** [comment] 2021-01-08 13:39
May I suggest something like this:

![printing](https://user-images.githubusercontent.com/76840398/104021444-6fbe0d00-51c7-11eb-9811-e3dd2fea2633.png)

**Comment by dryphi** [comment] 2021-01-08 14:11
> I believe it is helpful as a reminder, especially if someone is using various nozzles from different manufacturers.
> And more than once I have change it in real time when I noticed that the first layer didn't came out as expected.

How do you change the Z-height in real time?

**Comment by ztakis** [comment] 2021-01-08 15:06
By using the Tune screen.

**Comment by Thinkersbluff** [comment] 2021-01-10 02:37
Since we can now tap to change many of the parameters displayed in the footer of the Printing Screen, the only two parameters we need the Tune screen for are LED ON/OFF and Z Offset...  I could live with shorter pushbuttons if it created the missing real-estate for those controls on the Printing screen.

**Comment by ztakis** [comment] 2021-01-10 07:15
That's a great idea! Why not abolish the Tune button all together, then make the Pause and Stop buttons horizontal, one next to the other like the CONFIRM/CANCEL buttons. Then there should be enough space for LED ON/OFF and Z Offset.

**Comment by Thinkersbluff** [comment] 2021-01-10 15:28
To play “Devil’s Advocate”, though, the current ability “to tap to modify” those parameters is not self-evident, while the “Tune” button is...
Users familiar with stock and previous menus would start posting a lot of questions if the Tune button suddenly disappeared.

**Comment by Sebazzz** [comment] 2021-01-10 15:38
I agree. The tap to modify function is just a little extra for the ones who know how to find it. And the tuning screen is still there for firmware retraction, LED control etc.

**Comment by Thinkersbluff** [comment] 2021-01-10 15:53
This seems like a relevant test-case for structuring decisions about the future menu tree, under issue #121 

As someone who does know that tap to modify is there, I sometimes find myself wishing that either the M117 messaging was also on the Tune menu (because then I could just sit on the Tune menu & monitor my print) or that the Z Offset was also available to tap to modify on the Print screen (to try to improve a first layer in real-time.)

You @Sebazzz have the "unfair advantage" of having already started experimenting with live firmware retraction settings, which we have not.  I am sure the optimal menu structure should be workflow-oriented, to create screens optimized for what I will want to do while I am doing that workflow.  Question will be whether all possible scenarios of the entire printing workflow can be supported on a single screen (highly unlikely if you keep enriching the UI) and if not, which sets of functions should be grouped together for best effect?

**Comment by ztakis** [comment] 2021-02-24 19:42
In order to close this, I submit these variations of the printing screen which I think have the potential to satisfy most users and seem not too difficult to implement:

![printing1](https://user-images.githubusercontent.com/76840398/109056440-19f6e300-76e9-11eb-9302-2458365fbf04.png)

![printing2](https://user-images.githubusercontent.com/76840398/109056448-1a8f7980-76e9-11eb-90d9-70072272d839.png)

![printing3](https://user-images.githubusercontent.com/76840398/109056449-1a8f7980-76e9-11eb-805f-e43543fc8364.png)

**Comment by Sebazzz** [comment] 2021-02-24 19:49
Good input, thank you.

I like the second the most, but I do worry about the ability of DWIN to render the X/Y/Z values that small _and_ readable. Needs some experimentation I guess. For the status I'd abbreviate Linear Advance Factory to simply LA. 

More personal opinion: I don't like the LED button in the middle of the other values; I also doubt the value of needing to have that LED so accessible. Regardless, it looks out of place to me 🙂

**Comment by ztakis** [comment] 2021-02-24 19:53
For Linear Advance Factor you might use K-factor also but LA is fine too.
As for the LED, you might want to replace it with the retraction override button or indicator (not touchable)
Personally I use the LED often to check the printing progress and how clean the nozzle is.
That's an older variation:

![printing4](https://user-images.githubusercontent.com/76840398/109058531-c3d76f00-76eb-11eb-8082-e5c982f18990.png)

**Comment by rockymtngeek** [comment] 2021-02-24 20:06
@ztakis I like that location of the LED button as well as the rest in your last screenshot.

**Comment by Sebazzz** [comment] 2021-02-24 20:10
> For Linear Advance Factor you might use K-factor also but LA is fine too.

I thought of that, but the K-factor is an even more obscure term. K refers to the K in the linear advance formula. 

For the retract override we currently have these icons: 

![4_Retract_override_OFF](https://user-images.githubusercontent.com/1426097/109059595-b2d72f80-76e4-11eb-97d8-5307d54d3655.png)
![3_Retract_override_ON](https://user-images.githubusercontent.com/1426097/109059597-b36fc600-76e4-11eb-9df2-cb78bb26721f.png)

**Comment by Sebazzz** [comment] 2021-02-24 20:12
BTW: I would opt for a combination of the older design and the second design: X/Y/Z at the bottom, LED in the top bar, and a retract override indicator at the status part.

**Comment by ztakis** [comment] 2021-02-24 20:18
I agree for that combination.
For retract override you have these toggles too

![9_FWRetract_on](https://user-images.githubusercontent.com/76840398/109060235-d783d500-76ed-11eb-8aa8-a91880f6b70f.png)
![10_FWRetract_off](https://user-images.githubusercontent.com/76840398/109060248-da7ec580-76ed-11eb-92b0-5a9cc94387d3.png)

 We can make something squarish out of that

**Comment by Sebazzz** [comment] 2021-02-24 20:25
Yes, perhaps for the status part just retain the icon without the label.

**Comment by ztakis** [comment] 2021-02-24 21:24
![printing5](https://user-images.githubusercontent.com/76840398/109067604-66e1b600-76f7-11eb-9e57-b6ce1472b358.png)

**Comment by Sebazzz** [comment] 2021-02-24 21:25
Yes, exactly like that 😄

**Comment by ztakis** [comment] 2021-02-24 21:28
Glad you like it :)

**Comment by Sebazzz** [comment] 2021-02-24 21:32
So, going forward: 

I'Il assume you don't want to get into that DWIN rabbit hole, and also assume you mocked that up in Photoshop/GIMP 😉

Would it be possible to update the [appropriate PSD here](https://github.com/CR6Community/CR-6-touchscreen/tree/extui/gfx) with the screen (without the M117 and X/Y/Z placeholders). and create a "print paused" and "print finished" variant of this as well? For import in DWIN BMPs need to be exported from the PSD as well. (FYI @grobux )

Thanks again.

**Comment by ztakis** [comment] 2021-02-24 21:35
Believe it or not I made all this with Paint 3D. But yeah I'll give it a try with gimp.

**Comment by ztakis** [comment] 2021-04-13 16:36
@Sebazzz Shouldn't we close this?

**Comment by Sebazzz** [comment] 2021-04-13 16:54
You're right. don't know how this slipped through the net 😄

**Closed as completed** 2021-04-13 16:54 UTC
Labels: t:enhancement, good first issue
