### ISSUE TITLE
[BUG] Lock up after stopped print

### ISSUE THREAD

**Issue by crysalis010** [CR6Community/Marlin#25] opened 2020-10-28 01:31 UTC
When stopping a print from touchscreen, the print successfully stops, but screen locks up at the confirmation page. Must reboot in order to start over.

**Comment by Doridian** [comment] 2020-10-28 01:35
I am 99.9% sure this is because of https://github.com/CR6Community/Marlin/commit/1ed291cede7b6e5df114b97fce52622b4b929baa
I remember reading this as a "known issue", but can't find it documented anymore.
It fixes one bug (possible physical damage to your printer) by replacing it with another (hanging on the abort screen)

**Comment by Sebazzz** [comment] 2020-10-28 09:20
I don't see how that could cause it. There is no real difference between executing one gcode or the other.

As mentioned in the release notes, we need logging to diagnose this. Please provide some 👍

**Comment by crysalis010** [comment] 2020-10-28 12:05
I’m happy to provide logs if told where to find them/get them.

**Comment by starfuryth** [comment] 2020-10-28 12:45
+1
Updated firmware yesterday, ran straight into this issue.

**Comment by martinbogo** [comment] 2020-10-28 20:29
I have also reproduced this issue.   If you start a print, then stop it from the touchscreen, the screen locks up at the confirmation page and accepts no further input.

**Comment by Doridian** [comment] 2020-10-28 20:31
I knew I read it somewhere: https://github.com/CR6Community/Marlin/pull/13
`This does introduce a problem of the screen freezing on the "Stop Printing?" screen`

**Comment by Sebazzz** [comment] 2020-10-28 20:37
Fixed on extui branch

**Comment by Sebazzz** [comment] 2020-11-01 22:01
Ready for next release.

**Closed as completed by Sebazzz** 2020-11-01 22:01 UTC
